CREATE TABLE IF NOT EXISTS users (
    user_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255)  NOT NULL,
    email     VARCHAR(255)  NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS requests (
    request_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(2000),
    requestor_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS items (
    item_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255)   NOT NULL,
    description  VARCHAR(2000)  NOT NULL,
    is_available BOOLEAN        NOT NULL DEFAULT TRUE,
    owner_id     BIGINT         NOT NULL REFERENCES users(user_id),
    request_id   BIGINT         REFERENCES requests(request_id)
);

CREATE TABLE IF NOT EXISTS bookings (
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP NOT NULL,
    end_date   TIMESTAMP NOT NULL,
    item_id    BIGINT    NOT NULL REFERENCES items(item_id) ON DELETE CASCADE,
    booker_id  BIGINT    NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    status     VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text       VARCHAR(2000) NOT NULL,
    item_id    BIGINT        NOT NULL REFERENCES items(item_id) ON DELETE CASCADE,
    author_id  BIGINT        NOT NULL REFERENCES users(user_id)
);